### ISSUE TITLE
Duplicate functionality of `fzp_mask` and `moe.generate.fresnel_zone_plate_aperture`

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#18]
`fzp_mask` should be deprecated in favor of `moe.generate.fresnel_zone_plate_aperture`.

**Comment by cunhaJ** [comment]
Deprecation note added as of minor release 1.1, see f11f4e7e58d2f0fadb1e839a61c9cfcce9af47d7 . Major release will implement full deprecation. 
Closing this for now.
