### ISSUE TITLE
Move functionality of `save_mask_plot` from `generate.py` to `plotting.py` 

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#19]
`save_mask_plot` plots only the mask data while the `plotting.plot_aperture` includes all axis etc.
This functionality can be added to existing functions or to a new method. 

Be aware that `plt.pcolormesh` and `plt.imshow` do not give the same results. `imshow` has 1:1 aspect ratio, and plots all datapoints, but `pcolormesh` may not plot the last row or column entirely. This is more easily observable in small NxM matrices. 

The output of `imshow` would be more appropriate.

**Comment by daguiam** [comment]
Suggestion: Move to `export.py` and add `.bmp` output as a possibility.

**Comment by cunhaJ** [comment]
As of commit fd4eae6f2aa6a5bda4a779044baa8a734d5f80b6, version 1.1, `save_mask_plot` is now a plotting.py module function. 
Since same commit, saving as .bmp is supported (natively through use of opencv `imwrite`).
