### ISSUE TITLE
`fresnel_phase_mask` to be deprecated in favor of `moe.generate.fresnel_phase`

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#21]
`moe.generate.fresnel_phase` uses the Aperture architecture and should be favored. 

`fresnel_phase_mask` is legacy and shall be deprecated and removed from all notebooks

**Comment by cunhaJ** [comment]
Deprecation note added as of minor release 1.1, see f11f4e7e58d2f0fadb1e839a61c9cfcce9af47d7 . Major release will implement full deprecation. 
Closing this for now.
