### ISSUE TITLE
`arbitrary_phase_mask` and `arbitrary_multilayer_mask` to be deprecated in favor of `moe.generate.arbitrary_aperture_function`

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#22]
`moe.generate.arbitrary_aperture_function` honors the Aperture architecture using `sag_function.py` functions to produce the arbitrary shape.

`arbitrary_phase_mask` and `arbitrary_multilayer_mask` are legacy to be deprecated and should be removed from all notebooks.

**Comment by cunhaJ** [comment]
Deprecation note added as of minor release 1.1, see f11f4e7e58d2f0fadb1e839a61c9cfcce9af47d7 . Major release will implement full deprecation. 
Closing this for now.
