### ISSUE TITLE
Functionality of functions inside `importing.py` is not clear from module name

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#23]
The functions inside `importing.py` are auxiliary functions related to opening gds files and inspecting them by plotting with matplotlib, or to reconvert them. 
This is not exactly clear with the `importing.py` module name. Can it be changed to a more descriptive name such as `auxiliary` or `auxiliar_inspection`?

**Comment by daguiam** [comment]
There are also `inspect_XXX` functions inside `gds_klops.py` that should be verified together with these ones.

**Comment by cunhaJ** [comment]
Changing the name at this point of development is not forecasted. The naming of the modules does not impacts functionality or performance.
