### ISSUE TITLE
Update `propagate.py` module to include kernels and compatible with Aperture classes

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#24]
The `propagate.py` module shall include kernels for each propagation method and approximation (Fresnel, Fraunhofer, RS, etc), which should take as input the field array. 

Also, interface functions should take as input the Aperture class and its methods/parameters, and then call the respective kernel to propagate the field accordingly.

**Comment by cunhaJ** [comment]
Rudimentary kernel functions have been defined in version 1.2.1.

Next subversion (1.2.2) should consider better integration of ``propagate`` functions with the Aperture class for seemless use.
