### ISSUE TITLE
Add output/screen mesh to the RS propagation

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#32]
The RS propagation functions should either 1. receive a screen meshgrid as input, or 2. return the calculated meshgrid as output.

For 1. the meshgrid could be calculated previously, and can be non-regular or anything, and passed as input the the RS function to validate the field at that location.

For 2. a calculated meshgrid in addition to the evaluated field must be return as output. This way we are sure of the field locations where it is evaluated. 

As it currently is, the screen meshgrid is calculated from the parameters passed as input, but is never returned, which forces the user to recalculate the meshgrid outside in order to plot it correctly.

My preference would be for option 1 as it is more versatile.

**Comment by cunhaJ** [comment]
Solved by introduction of Field and Screen classes from commit a9da9ada7125e0dd5414eba87f8ce96f340410ce and 3f035f9740b730c164be410ba3c200321cd1dea9.
