### ISSUE TITLE
Field/Screen seem to be transposed.

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#35]
When plotting the aperture, and then plotting the propagated field, the obtained field appears to be transposed when compared to the original aperture.
Probably related to the `xy` and `ij` properities of `np.meshgrid`.

**Comment by cunhaJ** [comment]
I could reproduce this issue, which was evident in propagations of 1D Dammann Gratings (result was perpendicular to direction of periodicity of the grating).  

Issue was linked to `ij` indexing, as pointed originally by the Issue comment, in Screen class.
Issue resolved in commits e5f15478f8dcd60fc2096e9640e08e79b8674fac and also required minor tweaks in plotting functions in e47ec4022b78f06c910a47ae30e614935fcbc024.
