### ISSUE TITLE
moe.plotting.plot_screen_YZ results in swapped YZ labels

### ISSUE THREAD

**Issue by aamodsh** [INLnano/pyMOE#38]
$ \phi = \frac{2\pi }{\lambda}d $

```
moe.plotting.plot_screen_YZ(E_YZ, which='amplitude')
line 2
plt.plot
```

![image](https://github.com/INLnano/pyMOE/assets/4984671/646fe656-2f03-4813-8266-d7d79b29d555)

**Comment by cunhaJ** [comment]
As far as I could see this has been solved by merge 7bc90822ffda0617f8ec715e533377448ce86a1c . Closing it for now.
