### ISSUE TITLE
Meshgrid XX YY as inputs

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#6]
Calculate the space meshgrid outside using variables XX YY for example, and use the variables XX and YY as inputs for each mask generation function.

**Comment by cunhaJ** [comment]
In the commit 1835937e440c9d85e0807a59bb44ba2689a1ec8b this option was added. 
If no meshgrid is given as input, the meshgrid is remade based on npix, xsize and ysize each time the function is called.
