### ISSUE TITLE
Separate GDS generation from the mask generation

### ISSUE THREAD

**Issue by daguiam** [INLnano/pyMOE#9]
We first generate the mask array in memory, and must explicitly produce the GDS file from this mask outside the functions.

```
mask = generate_phase_mask(x,y, **params)
gds = create_gds_from_mask(mask, **params)

save_gds(gds, "output.gds))
```

**Comment by cunhaJ** [comment]
Implemented as of release 1.0, commit ceb4482cb88c71e868a4f613ffc1ec1f668291f7
